(() => {
  const panelsRoot = document.querySelector(".showcase-panels");
  if (!panelsRoot) return;

  const panels = Array.from(panelsRoot.querySelectorAll(".showcase-panel"));
  if (!panels.length) return;

  const desktopQuery = window.matchMedia("(min-width: 900px)");

  // --- Accordion state (used below the 900px desktop breakpoint) ---
  const setExpanded = (panel, expanded) => {
    panel.classList.toggle("is-expanded", expanded);
    panel
      .querySelector(".showcase-panel-trigger")
      ?.setAttribute("aria-expanded", String(expanded));
  };

  const collapseAll = () => panels.forEach((panel) => setExpanded(panel, false));

  // Keep the first category open by default, but only in accordion mode —
  // .is-expanded's visual effect (summary fade-in) isn't width-gated in
  // CSS, since it's shared with the desktop :hover/:focus-within reveal,
  // so it must never be set on desktop or panel 1 shows its summary at
  // rest while the other four don't.
  const applyDefaultExpansion = () => {
    if (desktopQuery.matches) {
      collapseAll();
    } else if (!panels.some((panel) => panel.classList.contains("is-expanded"))) {
      setExpanded(panels[0], true);
    }
  };

  applyDefaultExpansion();
  desktopQuery.addEventListener("change", applyDefaultExpansion);

  // --- Click behavior ---
  // Desktop (>=900px): hover/focus already drives the visual expand via
  // CSS; a click anywhere on the panel navigates immediately, keeping the
  // whole expanded panel clickable.
  // Below 900px: there's no separate CTA, so the panel itself is the
  // accordion header — tapping a collapsed panel opens it (revealing the
  // summary); tapping it again while already open navigates.
  panels.forEach((panel) => {
    panel.addEventListener("click", (event) => {
      if (desktopQuery.matches) {
        const href = panel.dataset.href;
        if (href) window.location.href = href;
        return;
      }

      if (!event.target.closest(".showcase-panel-trigger")) return;

      const alreadyOpen = panel.classList.contains("is-expanded");
      if (alreadyOpen) {
        const href = panel.dataset.href;
        if (href) window.location.href = href;
        return;
      }

      event.preventDefault();
      collapseAll();
      setExpanded(panel, true);
    });
  });

  // --- Preview images & hover slideshow ---
  // Each panel draws only from its own category's previews (generated by
  // scripts/generate-home-previews.js into js/home-previews.js). At rest it
  // shows one randomly picked static image; while a mouse hovers it, it
  // crossfades through the rest in a shuffled order and stops on whatever
  // image is showing when the mouse leaves. Touch devices and reduced-motion
  // users only ever get the static image.
  const previews = window.HOME_GALLERY_PREVIEWS || {};
  const hoverQuery = window.matchMedia("(hover: hover) and (pointer: fine)");
  const reducedMotionQuery = window.matchMedia("(prefers-reduced-motion: reduce)");
  const SLIDE_MIN_MS = 800;
  const SLIDE_MAX_MS = 1200;

  const encodeAssetPath = (assetPath) => String(assetPath).split("/").map(encodeURIComponent).join("/");

  const shuffle = (list) => {
    const result = list.slice();
    for (let i = result.length - 1; i > 0; i -= 1) {
      const j = Math.floor(Math.random() * (i + 1));
      [result[i], result[j]] = [result[j], result[i]];
    }
    return result;
  };

  panels.forEach((panel) => {
    const media = panel.querySelector(".showcase-panel-media");
    const order = shuffle((previews[panel.dataset.category] || []).map(encodeAssetPath));
    if (!media || !order.length) return;

    const overlay = media.querySelector(".showcase-panel-overlay");
    const layers = [0, 1].map(() => {
      const img = document.createElement("img");
      img.className = "showcase-panel-img";
      img.alt = "";
      img.decoding = "async";
      media.insertBefore(img, overlay);
      return img;
    });

    // order[0] is the random static pick; the second layer stays empty
    // until the slideshow needs it.
    let front = 0;
    let position = 0;
    layers[0].loading = "lazy";
    layers[0].src = order[0];
    layers[0].classList.add("is-active");
    layers[0].addEventListener("error", () => layers[0].classList.remove("is-active"), { once: true });

    let running = false;
    let timer = 0;
    // Bumped on every start so a decode still in flight from an earlier
    // hover can't resume after a quick leave/re-enter and double the loop.
    let session = 0;

    const nextIndex = () => (position + 1) % order.length;

    // Warms the cache for just the upcoming image — never the whole set.
    const preloadNext = () => {
      const img = new Image();
      img.decoding = "async";
      img.src = order[nextIndex()];
    };

    const schedule = () => {
      timer = window.setTimeout(advance, SLIDE_MIN_MS + Math.random() * (SLIDE_MAX_MS - SLIDE_MIN_MS));
    };

    async function advance() {
      const current = session;
      const index = nextIndex();
      const back = layers[1 - front];
      if (back.getAttribute("src") !== order[index]) back.src = order[index];

      try {
        await back.decode();
      } catch {
        // Broken file: drop it from the rotation and carry on.
        order.splice(index, 1);
        if (index < position) position -= 1;
        if (running && current === session && order.length > 1) schedule();
        return;
      }
      if (!running || current !== session) return;

      back.classList.add("is-active");
      layers[front].classList.remove("is-active");
      front = 1 - front;
      position = index;
      preloadNext();
      schedule();
    }

    const start = () => {
      if (running || order.length < 2 || reducedMotionQuery.matches || !hoverQuery.matches) return;
      running = true;
      session += 1;
      preloadNext();
      schedule();
    };

    const stop = () => {
      running = false;
      window.clearTimeout(timer);
    };

    panel.addEventListener("pointerenter", (event) => {
      if (event.pointerType === "mouse") start();
    });
    panel.addEventListener("pointerleave", stop);
    reducedMotionQuery.addEventListener("change", stop);
  });
})();
